services:
  mongodb-database:
    image: mongo:latest
    container_name: mongodb-search
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    networks:
      - crypto_network

volumes:
  mongodb_data:

networks:
  crypto_network:
    name: crypto_network
    external: true 